### ISSUE TITLE
dbdeployer unpack does not handle symlinks

### ISSUE THREAD

**Issue by datacharmer** [datacharmer/dbdeployer#10]
When a tarball contains symlink, the unpack procedure does not act on them.

**Comment by datacharmer** [comment]
Fixed in [release 1.3.0](https://github.com/datacharmer/dbdeployer/releases/tag/1.3.0)

**Comment by fjssilva** [comment]
Doesn't look like it's fixed in 1.4.2.

It seems to work with MySql 5.7 and 8.0 but not with 5.5 and 5.6.

$ dbdeployer unpack mysql-5.6.40-linux-glibc2.12-x86_64.tar.gz 
Unpacking tarball mysql-5.6.40-linux-glibc2.12-x86_64.tar.gz to $HOME/Development/MySQL/binaries/5.6.40
.........100.........200&tar.Header{Typeflag:0x32, Name:"mysql-5.6.40-linux-glibc2.12-x86_64/lib/libmysqlclient_r.so", Linkname:"libmysqlclient.so", Size:0, Mode:511, Uid:7161, Gid:31415, Uname:"pb2user", Gname:"common", ModTime:time.Time{wall:0x0, ext:63655247372, loc:(*time.Location)(0x8381a40)}, AccessTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ChangeTime:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Devmajor:0, Devminor:0, Xattrs:map[string]string(nil), PAXRecords:map[string]string(nil), Format:0}
# ERROR: symlink libmysqlclient.so mysql-5.6.40-linux-glibc2.12-x86_64/lib/libmysqlclient_r.so: no such file or directory

**Comment by datacharmer** [comment]
I see what's happening.
In the latest tarballs for 5.5 and 5.6, the symlinks are listed before the real files. 
The way dbdeployer handles symlink currently cannot work, as it requires the file to exist. 
I need to see whether I can do the same thing that tar does (create a symlink before the referred file exists) or defer the symlink creation until the referred file is extracted.

**Comment by datacharmer** [comment]
Fixed in release 1.5.0
