### ISSUE TITLE
wrong version in error message 

### ISSUE THREAD

**Issue by lalitpercona** [datacharmer/dbdeployer#106]
**Describe the bug**
Using dbdeployer version 1.47.0 and trying to deeply pxc topology for 5.6.36 version but it's failing with error `creating sandbox: ''Xtradb Cluster' requires flavor 'pxc' version '5.6.14'+'`
looks like error message should have 5.7.14+  because even for  5.6.36 version which higher than 5.6.14+ `dbdeployer deploy replication --topology=pxc`  failing. 

It looks like its typo bug.

$ dbdeployer --version
dbdeployer version 1.47.0

for old dbdeployer version error message is valid and it has a version as 5.7.14+ in the error message.

Example:
dbdeployer version 1.33.0
$ dbdeployer deploy replication --topology=pxc ./5.6.36
error creating sandbox: ''Xtradb Cluster' requires flavor 'pxc' version **'5.7.14'+'**

**To Reproduce**
$ dbdeployer deploy replication --topology=pxc /opt/percona_xtradb_cluster/5.6.36
error creating sandbox: ''Xtradb Cluster' requires flavor 'pxc' version '5.6.14'+'

**Comment by datacharmer** [comment]
Hi
Thanks for reporting this issue.
The error message is correct. Percona XtraDB cluster can be installed since version 5.6.14, as you can see in the [downloads page](https://www.percona.com/downloads/Percona-XtraDB-Cluster-56/LATEST/).

The error message is triggered when dbdeployer doesn't recognise the binaries as being PXC. It may happen if you were using the binaries for the regular server.

There is, however, a different problem in the current version of dbdeployer. It fails to properly deploy PXC 5.6, because of a change made to satisfy PXC 8.0.
It will be fixed in the next release (1.48.0), which I have verified that can deploy PXC 5.6.36+.

**Comment by lalitpercona** [comment]
Hi, 
That's great, thank you for the update. I will try a new version.
and Thank you for the wonderful Tool :)

**Comment by datacharmer** [comment]
Fixed in [v1.49.0](https://github.com/datacharmer/dbdeployer/releases/tag/v1.49.0)
