### ISSUE TITLE
--skip-library-check (How do I find the missing libraries reported)

### ISSUE THREAD

**Issue by ChameleonDevil** [datacharmer/dbdeployer#112]
# Intro
According to the documentation on the homepage (and here on github):

> As of version 1.40.0, dbdeployer tries to detect whether the host has the necessary libraries installed. When missing libraries are detected, the deployment fails with an error showing the missing pieces. For example:

          $ dbdeployer deploy single 5.7
          $ 5.7 => 5.7.27
          error while filling the sandbox definition: missing libraries will prevent MySQL from deploying correctly
          client (/root/opt/mysql/5.7.27/bin/mysql): [	libncurses.so.5 => not found 	libtinfo.so.5 => not found]
          
          server (/root/opt/mysql/5.7.27/bin/mysqld): [	libaio.so.1 => not found 	libnuma.so.1 => not found]
          global: [libaio libnuma]

> Use --skip-library-check to skip this check

> If you use --skip-library-check, the above check won’t be performed, and the **deployment may fail and leave you with an incomplete sandbox**. Skipping the check may be justified when deploying a very old version of MySQL (4.1, 5.0, 5.1)"

# Issue
_Installation is on Ubuntu 20.04_
I am currently trying to install the found repository **MySQL v5.7.30** 

**_(`dbdeployer downloads get-by-version 5.7` doesn't detect the newest v5.7.31 which is available)_**

I unpacked the downloaded 5.7.30:
`dbdeployer unpack --sandbox-binary /var/www/mysql/binaries/ --sandbox-home /var/www/mysql/5.7.30/ mysql-5.7.30-linux-glibc2.12-x86_64.tar.gz`

It unpacks successfully.

Trying to deploy a test installation by default command-line:
`dbdeployer deploy single 5.7.30`
> error while filling the sandbox definition: sandbox binary directory /home/magentoadmin/opt/mysql not found

So since I used custom --sandbox-binary and --sandbox-home when unpacked, I try to deploy a test installation using the 'unpacked location':

`dbdeployer deploy --sandbox-binary /var/www/mysql/binaries/ single 5.7.30`
This gives me the quoted error above (specifically file `libncurses.so.5 => not found`)

# Questions
- How do I use sandbox binary for custom locations, I plan to install 5.7.30, 8.0, MariaDB installations, and would like them all to be at a location I can find easier until I am familiar with the usage (and later 5.7.31 when it is supported by Dbdeployer) 
_(did I use that correctly?)_

- Without skipping (using `--skip-library-check`) how would I find the missing files to ensure a **'complete sandbox'**

**Comment by ChameleonDevil** [comment]
_I think_ I solved it...

Installed the library to get `libncurses.5.so`
`sudo apt-get install libncurses5`

(Internet suggestions for it mentioned `libncurses5-dev`, but this file is not in that library)

Found  the file now in so many different locations, not sure which is used :/

Then ran:
`dbdeployer init --sandbox-binary /var/www/mysql/binaries --sandbox-home /var/www/mysql/sandboxes`
`dbdeployer deploy single 5.7.30`

I was now able to create a new single instance.

**Comment by datacharmer** [comment]
> doesn't detect the newest v5.7.31 which is available)

The versions in `dbdeployer downloads` are updated manually. Until Oracle implements a downloads API instead of leaving often changing URLs for various versions, this is how it is. The items will be updated when I have time (or when I don't forget to do it: at every release, there are three or four new entries for both Linux and MacOS). You can add a download item (`dbdeployer downloads export --add-empty-item filename` and then edit and import it with `dbdeployer downloads import filename`) or you can download manually from MySQL site.
If you want to add an item to the [downloads JSON file](https://github.com/datacharmer/dbdeployer/blob/master/downloads/tarball_list.json) I will welcome a pull request that does it.

> How do I use sandbox binary for custom locations, I plan to install 5.7.30, 8.0, MariaDB installations, and would like them all to be at a location I can find easier until I am familiar with the usage

I strongly suggest using the default location for sandbox-binary, and using prefixes to differentiate between same version of different flavors. I use `ps` for Percona Server, `ndb` for MySQL Cluster, `ma` for MariaDb server. The prefix is added easily when you unpack : `dbdeployer unpack tarball_name --prefix=ps`.
I especially advise against mixing up paths. Leaving your sandboxes under `/var/www` looks like a bad idea. Given that dbdeployer was designed for ease of testing as a non-privileged user, having the binaries in user space (`/home/username/somepath`) is better than having them global.

> Without skipping (using --skip-library-check) how would I find the missing files to ensure a 'complete sandbox'

There is no sure way for this. When you use a new version of your OS or a new version of the server you mat find that the server requires a library that is not yet installed in your box. The best I could do was making dbdeployer smart enough to show the missing libraries without leaving users with an incomplete sandbox. How to install the missing libraries is usually a matter of a two-step process:

1. ask your package manager for the missing library (`apt search library_name` or `yum search library_name`). In some cases you may need to refresh the package list first.
2. install the package found. Not always easy, but you may get used to it.

You can find the definitions of some of my testing containers for CentOS and Ubuntu at [mysql-docker-minimal](https://github.com/datacharmer/mysql-docker-minimal/tree/master/mysql-docker-linux)

**Comment by ChameleonDevil** [comment]
Thank you @datacharmer for the advice ;)

I assumed the package information for versions were manual!

I have created an updated pull-request for the tarball_list.json as advised.   

_Please note the information I specified there about the behaviour of `dbdeployer downloads export/import`_ (not sure if it is intended or not)
[Pull Request 113](https://github.com/datacharmer/dbdeployer/pull/113)

Thanks!

**Comment by datacharmer** [comment]
There is no utility to move sandboxes. Each sandbox gets generated dynamically during deployment. By design, I chose not to add a `move` command, as it would make it more difficult to manage sandboxes, which should be in a centralized place.
The easiest way to move a sandbox is to delete it and deploy it again.

The hard way would be changing the values in sb_include, but then you need to modify the path to sb_include in all the depending scripts. It's the kind of task that dbdeployer **could** perform, but then there will be new problems. Until I find a valid workflow where a `move` command would make sense, I will sit on this.

**Comment by ChameleonDevil** [comment]
Hey @datacharmer, thanks for the information.  Before you replied, I figured out that there are alot of scripts where they use the same hard-coded paths.  I managed to move the instances, but it was so many files that I couldn't list them here.  Once I have some time (working full-time) I might look at how you could perform a move easier.  I already have an idea, but it is just high-level; and obviously need to test it when implemented.

**Comment by datacharmer** [comment]
Thanks for the info. 
Before you put too much effort into it, I need to see a good use case for moving sandboxes.
The current principles of `dbdeployer` are:

* Centralised sandboxes: dbdeployer can perform operations on many sandboxes (list, delete, start, stop, restart, run SQL command). This would not be easy if the sandboxes are under many separate paths.
* Centralised binaries: dbdeployer can search for earliest or latest versions of several subversions. This is fundamental to using dbdeployer inside scripts.

In the above scenarios, I don't see a need for moving sandboxes, unless you want to rename them. Unless you provide a convincing one, for which we could not see a workaround with current features and good practices, I am not going to consider such feature.
