### ISSUE TITLE
Unable to choose shell with --shell-path unless it's BASH

### ISSUE THREAD

**Issue by cezmunsta** [datacharmer/dbdeployer#126]
**Describe the bug**
When using cookbooks there is an option to set the path to the shell:
```sh
      --shell-path string       Which shell to use for generated scripts (default "/usr/bin/bash")
```
This clearly suggests that you can choose your shell, but it appears that you can only do so if it is BASH.

**To Reproduce**
1. `dbdeployer cookbook list --shell-path /usr/bin/bash`
2. `dbdeployer cookbook list --shell-path /usr/bin/zsh`
3. `dbdeployer cookbook list --shell-path /usr/bin/dash`

**Expected behavior**
The same output is expected for all commands, whereas only the one choosing BASH is successful.
For the other shells, an error is produced along the lines of:
```sh
error validating shell 'executable '<insert path used with shell-path>' does not appear to be a Bash interpreter'
```

**Environment:**
 - OS: Ubuntu 20.04
 - 1.44.0

**Comment by datacharmer** [comment]
Thanks for reporting this issue.

Sorry for the miscommunication. The shell **is expected** to be `bash`. Users can only change the path, when the default bash is outdated or otherwise inadequate.
It was not my intention to make all the scripts runnable by all shell interpreters. As it is today, `bash` is a hard requirement to run dbdeployer.

**Comment by cezmunsta** [comment]
OK, so presuming that the effort to make either POSIX-compliant scripts or shell-specific recipes is too great, I've added a PR that might help avoid the issue.
