### ISSUE TITLE
Include all from --my-cnf-file

### ISSUE THREAD

**Issue by fjssilva** [datacharmer/dbdeployer#13]
When deploying sandboxes with the option `--my-cnf-file` please include all contents (properties, comments and blank lines) in the corresponding section.

This is important because some options can't be set in the setup process, for example `default-time-zone` requires the time zones to be loaded beforehand. Including the original file allows me to come back later and tweak the generated `my.sandbox.cnf` and adjust it as needed.

Thanks,

**Comment by datacharmer** [comment]
I can add the requested behavior, but it will require an extra flag (e.g. `--use-whole-cnf`, but feel free to suggest a better one) because otherwise it would break compatibility for those users who are already relying on the current output.

Also notice the following:
1. dbdeployer skips all the options that are needed for sandbox functioning (user, socket, port, datadir, basedir, etc). I can add such options as comments instead of just skipping them, but I'd rather continue skipping them, as they may give users too much ammunition to shoot themselves in the foot.
2. Only the contents of `[mysqld]` are included in my.sandbox.cnf

**Comment by datacharmer** [comment]
Related info: it is possible to load the time zones using `--pre-grants-sql-file` or `--post-grants-sql-file` and then `./add_option` to modify my.sandbox.cnf on the fly, but it would require much precision.
I am thinking of adding an option `--load-time-zones`, but I need to see if the procedure can work across versions without much trouble.

**Comment by fjssilva** [comment]
Ok. I agree with both points.
Maybe `--my-cnf-no-sanitize`?... although you are always doing some level of sanitation. Perhaps something like `--my-cnf-sanitize-level int`, which could perform different levels of sanitation, say, 0 - current behavior; 1 - includes all but skips sandbox reserved options; 2 - includes all; or, instead of numbers, it could take keywords.

I have an issue with how the option `bind-address` is handled, though. It is added by default and you provide an option to override it, but there's no way to skip it altogether, right?

Nice that you mentioned the `--load-time-zones` option. This is something I've been doing manually in all my sandboxes for a long time. Actually I was about to write another feature request just for that.

I'd say that you should provide two options: `--load-time-zones` and `--tzinfo-source`. In Linux, I think you could chain a call to `${sandbox-binary}\bin\mysql_tzinfo_to_sql` and load from the directory `/usr/share/zoneinfo` by default and then run the SQL into the database `mysql` as required.
If the option `--tzinfo-source` is also given and it is a path, then use it in `mysql_tzinfo_to_sql`; if it points to a file (one of https://dev.mysql.com/downloads/timezones.html) then use it instead, although you may need some extra logic here to handle pre and post 5.7 versions. I'd say you should only allow the zipped files here.
In Windows, `--tzinfo-source` would be mandatory if `--load-time-zones` is used and must point to one of the zip files.
I was wondering if `--tzinfo-source` could, by default, search for an appropriate timezone_*.zip in current path if no better alternative was found i.e., if it wasn't set and/or `/usr/share/zoneinfo` doesn't exist, but this may be a little too risky.

If you decide to implement time zones loading then remains to decide when it should happen. Pre and post grants queries could be affected by the new database state.

Until there's no alternative, how can I use `--post-grants-sql-file` to load the time zones info? You also mentioned using `./add_option` which I could use to configure the time zone, but it would have to be called (manually) after `dbdeployer deploy ...`, right?

**Comment by datacharmer** [comment]
This feature needs some more thinking. I am not sure I will implement is very soon, as I need to avoid breaking anything. 
One thing that I am certain is that I won't skip sandbox reserved options, as this will break the sandbox behavior and create unnecessary problems for users who try it.

My suggestion about post grants + add_option requires some manual operations, yes. 

Please write a feature request about time zone, with the goals and possibly implementation suggestions. I have not worked much with time zones, and I may miss some nuances.

Finally, if having a customized my.sandbox.cnf is paramount for you, I forgot to mention that dbdeployer offers **two more ways** of customizing it.

1. Use your own permanent template:
    1a. run `$ dbdeployer defaults templates export single mytemplates my_cnf_template` to save the template to a file.
    1b. modify the template (`./mytemplates/single/my_cnf_template`) to suit your needs
    1c. Load your modified template. `$ dbdeployer defaults templates import single mytemplates my_cnf_template`
    1d. List the templates. `$ dbdeployer defaults template list single`. You will see that `my_cnf_template` has a `{F}` next to it, meaning that it's loaded from file instead of using the internal value. This template will be loaded from now on until you reset to internal values, or until dbdeployer changes the compatibility version (which happens when templates or defaults are changed.) 

2. Use a template on-the-fly
    2a. Get the template into a file like in the previous recipe.
    2b. Modify the template, and make as many versions as you need to fit different scenarios.
    2c. Load the template for a specific operation: 
    `dbdeployer deploy single 5.7.22 --use-template=my_cnf_template:/path/to/your/template`

This second solution allows you to load a different template for every special deployment.
In both cases you can remove bind-address or any other option. Be careful, though, because you may "brick" the sandbox if you remove vital options.

You can use all the `{{.Label}}` found in any of the templates in the `[single]` category, but not create new ones.

**Comment by fjssilva** [comment]
Thanks, I'll explore this solution. It may fit even better in my needs.

Regarding the time zones question, I'll think about it and file a request later if it comes to it. I have no time to do it right now.

Thanks again.

**Comment by datacharmer** [comment]
Please let me know if the templates solution works for you. If it does, I'd rather not do any change to `--my-cnf-file` and will just improve the docs.

**Comment by fjssilva** [comment]
Yes, customizing the template `my_cnf_template` works pretty well.

**Comment by datacharmer** [comment]
Considering that there is a reasonable alternative to this request, I am closing this issue.
Thanks for raising awareness on possible new features.
