### ISSUE TITLE
DBdeployer Mysql is not writting the error or slow logs 

### ISSUE THREAD

**Issue by jwnmohan** [datacharmer/dbdeployer#172]
We have a server running Linux and has DBdeployer configured and running with mysql . But its stopped writting the error log or slow message. Kindly advise how to check and fix this. 

We have compared the other servers are running fine with the similar setup or configuration. 

Thats my configuration and its path 

[mysqld]
user               = root
socket             = /tmp/mysql_sandbox43002.sock
basedir            = /opt/databases/binaries/mysql5.6.46
datadir            = /opt/databases/sandboxes/msb_mysql5_6_46/data
tmpdir             = /opt/databases/sandboxes/msb_mysql5_6_46/tmp
pid-file           = /opt/databases/sandboxes/msb_mysql5_6_46/data/mysql_sandbox43002.pid
log-error=/opt/databases/sandboxes/msb_mysql5_6_46/data/msandbox.err
slow_query_log = 1
slow_query_log_file = /opt/databases/sandboxes/msb_mysql5_6_46/data/msandbox.slow

Thats the permission and you can see its stopped writing and showing "0" . I could see the DB is running fine .  

-rw-r--r--   1 root root           0 Sep 24 06:40 msandbox.slow
-rw-rw----   1 root root           0 Sep 24 08:47 msandbox.err

**Comment by datacharmer** [comment]
I don't understand. You said that "it stopped writing", meaning that it was writing before. yet, the file size id "0", meaning that it has never written.
This behavior will only happen if you have deleted the files manually.
Have you tried restarting the sandbox?

**Comment by jwnmohan** [comment]
Yes, Its stopped writing , It was writing earlier . 

This behavior will only happen if you have deleted the files manually. -- No, We didnt deleted or performed any how clean or any major changes 
Have you tried restarting the sandbox? -- I tried rebooting the server and restarted the mysql DB as well service manually.

**Comment by datacharmer** [comment]
Sorry, I can't help you. What `dbdeployer` does is installing the database sandbox with the behavior you define.
As far as I can tell, it is doing it correctly.
The problem that you have happens after the deployment, meaning that it is a MySQL problem.
Moreover, there is a contradiction in your statement that the server was wiring before and now stopped, because the file has zero length. It is not possible that the server was writing and the file has no contents. So, either the server was never writing or the file was replaced.
