### ISSUE TITLE
Add support for replication across multiple versions

### ISSUE THREAD

**Issue by PrzemekMalkowski** [datacharmer/dbdeployer#28]
I would absolutely love to see the functionality like:
`dbdeployer deploy replication --master-ver=5.6.35 --slave-versions="5.6.40,5.7.22"`

**Comment by datacharmer** [comment]
It should be doable. It only requires some time to avoid breaking other functionalities.

Specifically, this feature must work together with :

* the main definition of a version (`dbdeployer deploy replication 5.6.41`). This could be fixed by using the main version (5.6.41 in the previous example) as the master version.
* the emergency definition of the working version (`dbdeployer deploy --binary-version=xxx ...`).

Another issue could be different topologies that don't use _slaves_, such as group replication or multi-source. I don't even know if GR would work with servers of different versions.

Anyway, I have several issues to tackle before this one. I am open to suggestions (and to pull requests!)

**Comment by datacharmer** [comment]
dbdeployer version 1.26.0 implements replication between sandboxes. See [Replication between sandboxes](https://github.com/datacharmer/dbdeployer#Replication-between-sandboxes).
Using this feature, you can deploy sandboxes from various versions, and start replication between them.

**Comment by datacharmer** [comment]
In dbdeployer 1.27.0 there is a cookbook example of cross-version replication.

Run the following:
```
dbdeployer cookbook list
[...]

dbdeployer cookbook create replication_multi_versions
```
Then look at `recipes/replication-multi-versions.sh` and eventually run the example by providing three versions on the command line.
