### ISSUE TITLE
Switch build system to go modules + make file

### ISSUE THREAD

**Issue by morgo** [datacharmer/dbdeployer#60]
**Is your feature request related to a problem? Please describe.**

I took a look at `./scripts/build.sh` and it looks to be doing dependency management.  There is nothing wrong with it, but I wonder if it would be more accessible to contributors if it were replaced by a makefile + use go 1.11 modules.

**Describe the solution you'd like**

`./scripts/build.sh` would become `make all` or `make linux`.

**Describe alternatives you've considered**

The alternative would be to implement part of this (go modules only), or leave as is.  This is a fairly function neutral enhancement.

**Additional context**

I am happy to contribute.  Just wanted to create an issue to discuss first.

**Comment by datacharmer** [comment]
The dependency management in `build.sh` has been there from before I started using the `./vendor` folder. It is now unnecessary and could be removed.

I won't use a Makefile because I have a personal aversion to it. I am investigating the use of [Mage](https://magefile.org) which produces more readable and maintainable code.

Regarding go modules, I have a hard problem with it. One of the Cobra menu features (using arguments that collect an array of values such as `--pre-grants-sql`) depends on `pflag` package,  which needs a tiny but vital customisation to be used effectively with MySQL options. As it is now, switching to modules would lose this customisation and I would have to perform heavy changes.

If there is a solution to this conundrum, I'd like to know.

**Comment by morgo** [comment]
no problems :-)  the current solution is also working fine.  I will close this issue now.
