### ISSUE TITLE
Question - how to upgrade from mysql sandbox

### ISSUE THREAD

**Issue by ms502040** [datacharmer/dbdeployer#90]
Can you write instruction / script / command to upgrade sandboxes instaled by mysql sandbox to dbdeployer sandboxes without data lost?

btw thx for great software!

**Comment by datacharmer** [comment]
Thanks for using dbdeployer.

Sandboxes installed by MySQL-sandbox are compatible, up to a point, with dbdeployer, meaning that dbdeployer recognises them and can do some operations (such as listing, locking, unlocking, and deleting sandboxes).

Given that sandboxes were not designed to be permanent, the best course of action is:
1. make a backup somewhere outside the sandbox
2. delete the sandbox
3. create a new sandbox using dbdeployer
4. restore the data.

**Comment by ms502040** [comment]
This is a bit complicated and time consuming method with a lot of sandboxes. May by simple update scripts in sandboxes?

**Comment by datacharmer** [comment]
My suggestion is based on the fact that sandboxes (both the old ones and the modern ones) are designed to be scriptable. As such, you should be able to figure out a script that fits your purpose.

An update script in sandboxes would mean updating MySQL-Sandbox to create such scripts, which is not worth doing. And besides, it would mean re-deploying the sandboxes, which is what I was suggesting already, but using dbdeployer.

If I had to write a procedure for upgrade – which nobody has ever asked for so far, since sandboxes are supposed to be used and deleted – I would need to:

1. make a lot of sandboxes with MySQL-Sandbox;
2. create a method for upgrading automatically;
3. test that it works as expected
4. repeat 1,2,3 until correct
5. Find a way of either distributing the script or integrate the upgrade procedure into dbdeployer.

Also this would be time consuming. Only it would be my time. I work on dbdeployer on my spare time, of which I don't have unlimited amounts. Thus, I code what I feel is most useful, and what I can do with pleasure.

Thus, I need to choose: either I spend my time implementing a feature with probable little benefit, or I continue improving dbdeployer in the direction that makes most people (including me) happy.

That said, if you have a procedure in mind, feel free to submit a proposal for integration, or fork the project to suit your needs.
